spring:
  application:
    name: USER-SERVICES
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/madeeasy_login
    username: user
    password: user
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    generate-ddl: true
    show-sql: true
  servlet:
    multipart:
      enabled: 'true'
      fileSizeThreshold: 2KB #after the fileSizeThreshold size file will be saved
      maxFileSize: 800MB
      maxRequestSize: 800MB